// Code generated by go-swagger; DO NOT EDIT.

package resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/craguilar/cidm/models"
)

// AddResourceOKCode is the HTTP code returned for type AddResourceOK
const AddResourceOKCode int = 200

/*AddResourceOK Successful operation

swagger:response addResourceOK
*/
type AddResourceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Resource `json:"body,omitempty"`
}

// NewAddResourceOK creates AddResourceOK with default headers values
func NewAddResourceOK() *AddResourceOK {
	return &AddResourceOK{}
}

// WithPayload adds the payload to the add resource o k response
func (o *AddResourceOK) WithPayload(payload *models.Resource) *AddResourceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add resource o k response
func (o *AddResourceOK) SetPayload(payload *models.Resource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddResourceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddResourceNotFoundCode is the HTTP code returned for type AddResourceNotFound
const AddResourceNotFoundCode int = 404

/*AddResourceNotFound Resource not found

swagger:response addResourceNotFound
*/
type AddResourceNotFound struct {
}

// NewAddResourceNotFound creates AddResourceNotFound with default headers values
func NewAddResourceNotFound() *AddResourceNotFound {
	return &AddResourceNotFound{}
}

// WriteResponse to the client
func (o *AddResourceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*AddResourceDefault Unexpected error

swagger:response addResourceDefault
*/
type AddResourceDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddResourceDefault creates AddResourceDefault with default headers values
func NewAddResourceDefault(code int) *AddResourceDefault {
	if code <= 0 {
		code = 500
	}

	return &AddResourceDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add resource default response
func (o *AddResourceDefault) WithStatusCode(code int) *AddResourceDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add resource default response
func (o *AddResourceDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add resource default response
func (o *AddResourceDefault) WithPayload(payload *models.Error) *AddResourceDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add resource default response
func (o *AddResourceDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddResourceDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
