// Code generated by go-swagger; DO NOT EDIT.

package resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/craguilar/cidm/models"
)

// DeleteResourceOKCode is the HTTP code returned for type DeleteResourceOK
const DeleteResourceOKCode int = 200

/*DeleteResourceOK Successful operation

swagger:response deleteResourceOK
*/
type DeleteResourceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Resource `json:"body,omitempty"`
}

// NewDeleteResourceOK creates DeleteResourceOK with default headers values
func NewDeleteResourceOK() *DeleteResourceOK {
	return &DeleteResourceOK{}
}

// WithPayload adds the payload to the delete resource o k response
func (o *DeleteResourceOK) WithPayload(payload *models.Resource) *DeleteResourceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resource o k response
func (o *DeleteResourceOK) SetPayload(payload *models.Resource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteResourceNotFoundCode is the HTTP code returned for type DeleteResourceNotFound
const DeleteResourceNotFoundCode int = 404

/*DeleteResourceNotFound Resource not found

swagger:response deleteResourceNotFound
*/
type DeleteResourceNotFound struct {
}

// NewDeleteResourceNotFound creates DeleteResourceNotFound with default headers values
func NewDeleteResourceNotFound() *DeleteResourceNotFound {
	return &DeleteResourceNotFound{}
}

// WriteResponse to the client
func (o *DeleteResourceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*DeleteResourceDefault Unexpected error

swagger:response deleteResourceDefault
*/
type DeleteResourceDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteResourceDefault creates DeleteResourceDefault with default headers values
func NewDeleteResourceDefault(code int) *DeleteResourceDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteResourceDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete resource default response
func (o *DeleteResourceDefault) WithStatusCode(code int) *DeleteResourceDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete resource default response
func (o *DeleteResourceDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete resource default response
func (o *DeleteResourceDefault) WithPayload(payload *models.Error) *DeleteResourceDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resource default response
func (o *DeleteResourceDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourceDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
