// Code generated by go-swagger; DO NOT EDIT.

package resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteResourceHandlerFunc turns a function with the right signature into a delete resource handler
type DeleteResourceHandlerFunc func(DeleteResourceParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteResourceHandlerFunc) Handle(params DeleteResourceParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteResourceHandler interface for that can handle valid delete resource params
type DeleteResourceHandler interface {
	Handle(DeleteResourceParams, interface{}) middleware.Responder
}

// NewDeleteResource creates a new http.Handler for the delete resource operation
func NewDeleteResource(ctx *middleware.Context, handler DeleteResourceHandler) *DeleteResource {
	return &DeleteResource{Context: ctx, Handler: handler}
}

/*DeleteResource swagger:route DELETE /resource/ resource deleteResource

Delete Resource details by Id

Get a particular resource by Id


*/
type DeleteResource struct {
	Context *middleware.Context
	Handler DeleteResourceHandler
}

func (o *DeleteResource) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteResourceParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
