// Code generated by go-swagger; DO NOT EDIT.

package resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/craguilar/cidm/models"
)

// GetResourceByIDOKCode is the HTTP code returned for type GetResourceByIDOK
const GetResourceByIDOKCode int = 200

/*GetResourceByIDOK Successful operation

swagger:response getResourceByIdOK
*/
type GetResourceByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Resource `json:"body,omitempty"`
}

// NewGetResourceByIDOK creates GetResourceByIDOK with default headers values
func NewGetResourceByIDOK() *GetResourceByIDOK {
	return &GetResourceByIDOK{}
}

// WithPayload adds the payload to the get resource by Id o k response
func (o *GetResourceByIDOK) WithPayload(payload *models.Resource) *GetResourceByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get resource by Id o k response
func (o *GetResourceByIDOK) SetPayload(payload *models.Resource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResourceByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetResourceByIDNotFoundCode is the HTTP code returned for type GetResourceByIDNotFound
const GetResourceByIDNotFoundCode int = 404

/*GetResourceByIDNotFound Resource not found

swagger:response getResourceByIdNotFound
*/
type GetResourceByIDNotFound struct {
}

// NewGetResourceByIDNotFound creates GetResourceByIDNotFound with default headers values
func NewGetResourceByIDNotFound() *GetResourceByIDNotFound {
	return &GetResourceByIDNotFound{}
}

// WriteResponse to the client
func (o *GetResourceByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*GetResourceByIDDefault Unexpected error

swagger:response getResourceByIdDefault
*/
type GetResourceByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetResourceByIDDefault creates GetResourceByIDDefault with default headers values
func NewGetResourceByIDDefault(code int) *GetResourceByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetResourceByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get resource by Id default response
func (o *GetResourceByIDDefault) WithStatusCode(code int) *GetResourceByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get resource by Id default response
func (o *GetResourceByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get resource by Id default response
func (o *GetResourceByIDDefault) WithPayload(payload *models.Error) *GetResourceByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get resource by Id default response
func (o *GetResourceByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResourceByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
