// Code generated by go-swagger; DO NOT EDIT.

package resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateResourceHandlerFunc turns a function with the right signature into a update resource handler
type UpdateResourceHandlerFunc func(UpdateResourceParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateResourceHandlerFunc) Handle(params UpdateResourceParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateResourceHandler interface for that can handle valid update resource params
type UpdateResourceHandler interface {
	Handle(UpdateResourceParams, interface{}) middleware.Responder
}

// NewUpdateResource creates a new http.Handler for the update resource operation
func NewUpdateResource(ctx *middleware.Context, handler UpdateResourceHandler) *UpdateResource {
	return &UpdateResource{Context: ctx, Handler: handler}
}

/*UpdateResource swagger:route PUT /resource/ resource updateResource

Update Resource details by Id

Get a particular resource by Id


*/
type UpdateResource struct {
	Context *middleware.Context
	Handler UpdateResourceHandler
}

func (o *UpdateResource) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateResourceParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
