// Code generated by go-swagger; DO NOT EDIT.

package resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/craguilar/cidm/models"
)

// UpdateResourceOKCode is the HTTP code returned for type UpdateResourceOK
const UpdateResourceOKCode int = 200

/*UpdateResourceOK Successful operation

swagger:response updateResourceOK
*/
type UpdateResourceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Resource `json:"body,omitempty"`
}

// NewUpdateResourceOK creates UpdateResourceOK with default headers values
func NewUpdateResourceOK() *UpdateResourceOK {
	return &UpdateResourceOK{}
}

// WithPayload adds the payload to the update resource o k response
func (o *UpdateResourceOK) WithPayload(payload *models.Resource) *UpdateResourceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update resource o k response
func (o *UpdateResourceOK) SetPayload(payload *models.Resource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateResourceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateResourceNotFoundCode is the HTTP code returned for type UpdateResourceNotFound
const UpdateResourceNotFoundCode int = 404

/*UpdateResourceNotFound Resource not found

swagger:response updateResourceNotFound
*/
type UpdateResourceNotFound struct {
}

// NewUpdateResourceNotFound creates UpdateResourceNotFound with default headers values
func NewUpdateResourceNotFound() *UpdateResourceNotFound {
	return &UpdateResourceNotFound{}
}

// WriteResponse to the client
func (o *UpdateResourceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*UpdateResourceDefault Unexpected error

swagger:response updateResourceDefault
*/
type UpdateResourceDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateResourceDefault creates UpdateResourceDefault with default headers values
func NewUpdateResourceDefault(code int) *UpdateResourceDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateResourceDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update resource default response
func (o *UpdateResourceDefault) WithStatusCode(code int) *UpdateResourceDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update resource default response
func (o *UpdateResourceDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update resource default response
func (o *UpdateResourceDefault) WithPayload(payload *models.Error) *UpdateResourceDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update resource default response
func (o *UpdateResourceDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateResourceDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
