// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Identity Manager
This is the base API for Identity Manager microservice. Api documentation
available in /api/idm/docs



    Schemes:
      http
    Host: localhost:30030
    BasePath: /api/idm
    Version: 1.0.0
    Contact: Carlos Ruiz<caruizag@gmail.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
