// Code generated by go-swagger; DO NOT EDIT.

package token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteUserPermissionHandlerFunc turns a function with the right signature into a delete user permission handler
type DeleteUserPermissionHandlerFunc func(DeleteUserPermissionParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteUserPermissionHandlerFunc) Handle(params DeleteUserPermissionParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteUserPermissionHandler interface for that can handle valid delete user permission params
type DeleteUserPermissionHandler interface {
	Handle(DeleteUserPermissionParams, interface{}) middleware.Responder
}

// NewDeleteUserPermission creates a new http.Handler for the delete user permission operation
func NewDeleteUserPermission(ctx *middleware.Context, handler DeleteUserPermissionHandler) *DeleteUserPermission {
	return &DeleteUserPermission{Context: ctx, Handler: handler}
}

/*DeleteUserPermission swagger:route DELETE /token/authorization/ token deleteUserPermission

Get all Permissions for a particular token .

Delete a permission.

*/
type DeleteUserPermission struct {
	Context *middleware.Context
	Handler DeleteUserPermissionHandler
}

func (o *DeleteUserPermission) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteUserPermissionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
