// Code generated by go-swagger; DO NOT EDIT.

package token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/craguilar/cidm/models"
)

// DeleteUserPermissionOKCode is the HTTP code returned for type DeleteUserPermissionOK
const DeleteUserPermissionOKCode int = 200

/*DeleteUserPermissionOK successful operation

swagger:response deleteUserPermissionOK
*/
type DeleteUserPermissionOK struct {
}

// NewDeleteUserPermissionOK creates DeleteUserPermissionOK with default headers values
func NewDeleteUserPermissionOK() *DeleteUserPermissionOK {
	return &DeleteUserPermissionOK{}
}

// WriteResponse to the client
func (o *DeleteUserPermissionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// DeleteUserPermissionUnauthorizedCode is the HTTP code returned for type DeleteUserPermissionUnauthorized
const DeleteUserPermissionUnauthorizedCode int = 401

/*DeleteUserPermissionUnauthorized Authentication information is missing or invalid

swagger:response deleteUserPermissionUnauthorized
*/
type DeleteUserPermissionUnauthorized struct {
	/*
	  Required: true
	*/
	WWWAuthenticate string `json:"WWW_Authenticate"`
}

// NewDeleteUserPermissionUnauthorized creates DeleteUserPermissionUnauthorized with default headers values
func NewDeleteUserPermissionUnauthorized() *DeleteUserPermissionUnauthorized {
	return &DeleteUserPermissionUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the delete user permission unauthorized response
func (o *DeleteUserPermissionUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *DeleteUserPermissionUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the delete user permission unauthorized response
func (o *DeleteUserPermissionUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *DeleteUserPermissionUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.WriteHeader(401)
}

/*DeleteUserPermissionDefault Unexpected error

swagger:response deleteUserPermissionDefault
*/
type DeleteUserPermissionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteUserPermissionDefault creates DeleteUserPermissionDefault with default headers values
func NewDeleteUserPermissionDefault(code int) *DeleteUserPermissionDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteUserPermissionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete user permission default response
func (o *DeleteUserPermissionDefault) WithStatusCode(code int) *DeleteUserPermissionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete user permission default response
func (o *DeleteUserPermissionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete user permission default response
func (o *DeleteUserPermissionDefault) WithPayload(payload *models.Error) *DeleteUserPermissionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user permission default response
func (o *DeleteUserPermissionDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserPermissionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
