// Code generated by go-swagger; DO NOT EDIT.

package token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/craguilar/cidm/models"
)

// TokenValidateOKCode is the HTTP code returned for type TokenValidateOK
const TokenValidateOKCode int = 200

/*TokenValidateOK Successful operation

swagger:response tokenValidateOK
*/
type TokenValidateOK struct {
}

// NewTokenValidateOK creates TokenValidateOK with default headers values
func NewTokenValidateOK() *TokenValidateOK {
	return &TokenValidateOK{}
}

// WriteResponse to the client
func (o *TokenValidateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// TokenValidateUnauthorizedCode is the HTTP code returned for type TokenValidateUnauthorized
const TokenValidateUnauthorizedCode int = 401

/*TokenValidateUnauthorized Authentication information is missing or invalid

swagger:response tokenValidateUnauthorized
*/
type TokenValidateUnauthorized struct {
	/*
	  Required: true
	*/
	WWWAuthenticate string `json:"WWW_Authenticate"`
}

// NewTokenValidateUnauthorized creates TokenValidateUnauthorized with default headers values
func NewTokenValidateUnauthorized() *TokenValidateUnauthorized {
	return &TokenValidateUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the token validate unauthorized response
func (o *TokenValidateUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *TokenValidateUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the token validate unauthorized response
func (o *TokenValidateUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *TokenValidateUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.WriteHeader(401)
}

/*TokenValidateDefault Unexpected error

swagger:response tokenValidateDefault
*/
type TokenValidateDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewTokenValidateDefault creates TokenValidateDefault with default headers values
func NewTokenValidateDefault(code int) *TokenValidateDefault {
	if code <= 0 {
		code = 500
	}

	return &TokenValidateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the token validate default response
func (o *TokenValidateDefault) WithStatusCode(code int) *TokenValidateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the token validate default response
func (o *TokenValidateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the token validate default response
func (o *TokenValidateDefault) WithPayload(payload *models.Error) *TokenValidateDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the token validate default response
func (o *TokenValidateDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TokenValidateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
