// Code generated by go-swagger; DO NOT EDIT.

package token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/craguilar/cidm/models"
)

// TokenValidatPayloadOKCode is the HTTP code returned for type TokenValidatPayloadOK
const TokenValidatPayloadOKCode int = 200

/*TokenValidatPayloadOK Valid Token

swagger:response tokenValidatPayloadOK
*/
type TokenValidatPayloadOK struct {
}

// NewTokenValidatPayloadOK creates TokenValidatPayloadOK with default headers values
func NewTokenValidatPayloadOK() *TokenValidatPayloadOK {
	return &TokenValidatPayloadOK{}
}

// WriteResponse to the client
func (o *TokenValidatPayloadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// TokenValidatPayloadUnauthorizedCode is the HTTP code returned for type TokenValidatPayloadUnauthorized
const TokenValidatPayloadUnauthorizedCode int = 401

/*TokenValidatPayloadUnauthorized Authentication information is missing or invalid

swagger:response tokenValidatPayloadUnauthorized
*/
type TokenValidatPayloadUnauthorized struct {
	/*
	  Required: true
	*/
	WWWAuthenticate string `json:"WWW_Authenticate"`
}

// NewTokenValidatPayloadUnauthorized creates TokenValidatPayloadUnauthorized with default headers values
func NewTokenValidatPayloadUnauthorized() *TokenValidatPayloadUnauthorized {
	return &TokenValidatPayloadUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the token validat payload unauthorized response
func (o *TokenValidatPayloadUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *TokenValidatPayloadUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the token validat payload unauthorized response
func (o *TokenValidatPayloadUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *TokenValidatPayloadUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.WriteHeader(401)
}

/*TokenValidatPayloadDefault Unexpected error

swagger:response tokenValidatPayloadDefault
*/
type TokenValidatPayloadDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewTokenValidatPayloadDefault creates TokenValidatPayloadDefault with default headers values
func NewTokenValidatPayloadDefault(code int) *TokenValidatPayloadDefault {
	if code <= 0 {
		code = 500
	}

	return &TokenValidatPayloadDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the token validat payload default response
func (o *TokenValidatPayloadDefault) WithStatusCode(code int) *TokenValidatPayloadDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the token validat payload default response
func (o *TokenValidatPayloadDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the token validat payload default response
func (o *TokenValidatPayloadDefault) WithPayload(payload *models.Error) *TokenValidatPayloadDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the token validat payload default response
func (o *TokenValidatPayloadDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TokenValidatPayloadDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
