// Code generated by go-swagger; DO NOT EDIT.

package token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// TokenValidatPayloadHandlerFunc turns a function with the right signature into a token validat payload handler
type TokenValidatPayloadHandlerFunc func(TokenValidatPayloadParams) middleware.Responder

// Handle executing the request and returning a response
func (fn TokenValidatPayloadHandlerFunc) Handle(params TokenValidatPayloadParams) middleware.Responder {
	return fn(params)
}

// TokenValidatPayloadHandler interface for that can handle valid token validat payload params
type TokenValidatPayloadHandler interface {
	Handle(TokenValidatPayloadParams) middleware.Responder
}

// NewTokenValidatPayload creates a new http.Handler for the token validat payload operation
func NewTokenValidatPayload(ctx *middleware.Context, handler TokenValidatPayloadHandler) *TokenValidatPayload {
	return &TokenValidatPayload{Context: ctx, Handler: handler}
}

/*TokenValidatPayload swagger:route POST /token/authentication token tokenValidatPayload

Validate token in header no need for authentication

Validate token

*/
type TokenValidatPayload struct {
	Context *middleware.Context
	Handler TokenValidatPayloadHandler
}

func (o *TokenValidatPayload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewTokenValidatPayloadParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
