// Code generated by go-swagger; DO NOT EDIT.

package token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/craguilar/cidm/models"
)

// NewUpdateUserPermissionParams creates a new UpdateUserPermissionParams object
// with the default values initialized.
func NewUpdateUserPermissionParams() UpdateUserPermissionParams {
	var ()
	return UpdateUserPermissionParams{}
}

// UpdateUserPermissionParams contains all the bound params for the update user permission operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateUserPermission
type UpdateUserPermissionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: header
	*/
	Authorization string
	/*
	  Required: true
	  In: body
	*/
	Permission *models.Permission
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *UpdateUserPermissionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if err := o.bindAuthorization(r.Header[http.CanonicalHeaderKey("Authorization")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Permission
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("permission", "body"))
			} else {
				res = append(res, errors.NewParseError("permission", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Permission = &body
			}
		}

	} else {
		res = append(res, errors.Required("permission", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateUserPermissionParams) bindAuthorization(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("Authorization", "header")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("Authorization", "header", raw); err != nil {
		return err
	}

	o.Authorization = raw

	return nil
}
