// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/craguilar/cidm/models"
)

// AddLoginDetailsCreatedCode is the HTTP code returned for type AddLoginDetailsCreated
const AddLoginDetailsCreatedCode int = 201

/*AddLoginDetailsCreated Created

swagger:response addLoginDetailsCreated
*/
type AddLoginDetailsCreated struct {
}

// NewAddLoginDetailsCreated creates AddLoginDetailsCreated with default headers values
func NewAddLoginDetailsCreated() *AddLoginDetailsCreated {
	return &AddLoginDetailsCreated{}
}

// WriteResponse to the client
func (o *AddLoginDetailsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
}

// AddLoginDetailsUnauthorizedCode is the HTTP code returned for type AddLoginDetailsUnauthorized
const AddLoginDetailsUnauthorizedCode int = 401

/*AddLoginDetailsUnauthorized Authentication information is missing or invalid

swagger:response addLoginDetailsUnauthorized
*/
type AddLoginDetailsUnauthorized struct {
	/*
	  Required: true
	*/
	WWWAuthenticate string `json:"WWW_Authenticate"`
}

// NewAddLoginDetailsUnauthorized creates AddLoginDetailsUnauthorized with default headers values
func NewAddLoginDetailsUnauthorized() *AddLoginDetailsUnauthorized {
	return &AddLoginDetailsUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the add login details unauthorized response
func (o *AddLoginDetailsUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *AddLoginDetailsUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the add login details unauthorized response
func (o *AddLoginDetailsUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *AddLoginDetailsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.WriteHeader(401)
}

/*AddLoginDetailsDefault Unexpected error

swagger:response addLoginDetailsDefault
*/
type AddLoginDetailsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddLoginDetailsDefault creates AddLoginDetailsDefault with default headers values
func NewAddLoginDetailsDefault(code int) *AddLoginDetailsDefault {
	if code <= 0 {
		code = 500
	}

	return &AddLoginDetailsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add login details default response
func (o *AddLoginDetailsDefault) WithStatusCode(code int) *AddLoginDetailsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add login details default response
func (o *AddLoginDetailsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add login details default response
func (o *AddLoginDetailsDefault) WithPayload(payload *models.Error) *AddLoginDetailsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add login details default response
func (o *AddLoginDetailsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddLoginDetailsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
