// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddLoginDetailsHandlerFunc turns a function with the right signature into a add login details handler
type AddLoginDetailsHandlerFunc func(AddLoginDetailsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn AddLoginDetailsHandlerFunc) Handle(params AddLoginDetailsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// AddLoginDetailsHandler interface for that can handle valid add login details params
type AddLoginDetailsHandler interface {
	Handle(AddLoginDetailsParams, interface{}) middleware.Responder
}

// NewAddLoginDetails creates a new http.Handler for the add login details operation
func NewAddLoginDetails(ctx *middleware.Context, handler AddLoginDetailsHandler) *AddLoginDetails {
	return &AddLoginDetails{Context: ctx, Handler: handler}
}

/*AddLoginDetails swagger:route POST /login login addLoginDetails

Add loging details.

Add new login handler , you can have multiple logins defined per IDM.


*/
type AddLoginDetails struct {
	Context *middleware.Context
	Handler AddLoginDetailsHandler
}

func (o *AddLoginDetails) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddLoginDetailsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
