// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/craguilar/cidm/models"
)

// GetLoginDetailsByIDOKCode is the HTTP code returned for type GetLoginDetailsByIDOK
const GetLoginDetailsByIDOKCode int = 200

/*GetLoginDetailsByIDOK Successful operation

swagger:response getLoginDetailsByIdOK
*/
type GetLoginDetailsByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Login `json:"body,omitempty"`
}

// NewGetLoginDetailsByIDOK creates GetLoginDetailsByIDOK with default headers values
func NewGetLoginDetailsByIDOK() *GetLoginDetailsByIDOK {
	return &GetLoginDetailsByIDOK{}
}

// WithPayload adds the payload to the get login details by Id o k response
func (o *GetLoginDetailsByIDOK) WithPayload(payload *models.Login) *GetLoginDetailsByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get login details by Id o k response
func (o *GetLoginDetailsByIDOK) SetPayload(payload *models.Login) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLoginDetailsByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetLoginDetailsByIDNotFoundCode is the HTTP code returned for type GetLoginDetailsByIDNotFound
const GetLoginDetailsByIDNotFoundCode int = 404

/*GetLoginDetailsByIDNotFound Loging not found

swagger:response getLoginDetailsByIdNotFound
*/
type GetLoginDetailsByIDNotFound struct {
}

// NewGetLoginDetailsByIDNotFound creates GetLoginDetailsByIDNotFound with default headers values
func NewGetLoginDetailsByIDNotFound() *GetLoginDetailsByIDNotFound {
	return &GetLoginDetailsByIDNotFound{}
}

// WriteResponse to the client
func (o *GetLoginDetailsByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*GetLoginDetailsByIDDefault Unexpected error

swagger:response getLoginDetailsByIdDefault
*/
type GetLoginDetailsByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetLoginDetailsByIDDefault creates GetLoginDetailsByIDDefault with default headers values
func NewGetLoginDetailsByIDDefault(code int) *GetLoginDetailsByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetLoginDetailsByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get login details by Id default response
func (o *GetLoginDetailsByIDDefault) WithStatusCode(code int) *GetLoginDetailsByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get login details by Id default response
func (o *GetLoginDetailsByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get login details by Id default response
func (o *GetLoginDetailsByIDDefault) WithPayload(payload *models.Error) *GetLoginDetailsByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get login details by Id default response
func (o *GetLoginDetailsByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLoginDetailsByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
