// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/craguilar/cidm/models"
)

// GetLoginOKCode is the HTTP code returned for type GetLoginOK
const GetLoginOKCode int = 200

/*GetLoginOK Successful operation ok - resource found

swagger:response getLoginOK
*/
type GetLoginOK struct {
}

// NewGetLoginOK creates GetLoginOK with default headers values
func NewGetLoginOK() *GetLoginOK {
	return &GetLoginOK{}
}

// WriteResponse to the client
func (o *GetLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// GetLoginFoundCode is the HTTP code returned for type GetLoginFound
const GetLoginFoundCode int = 302

/*GetLoginFound Successful operation ok - redirect to OAuth2

swagger:response getLoginFound
*/
type GetLoginFound struct {
	/*
	  Required: true
	*/
	Location string `json:"Location"`
}

// NewGetLoginFound creates GetLoginFound with default headers values
func NewGetLoginFound() *GetLoginFound {
	return &GetLoginFound{}
}

// WithLocation adds the location to the get login found response
func (o *GetLoginFound) WithLocation(location string) *GetLoginFound {
	o.Location = location
	return o
}

// SetLocation sets the location to the get login found response
func (o *GetLoginFound) SetLocation(location string) {
	o.Location = location
}

// WriteResponse to the client
func (o *GetLoginFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.WriteHeader(302)
}

/*GetLoginDefault Unexpected error

swagger:response getLoginDefault
*/
type GetLoginDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetLoginDefault creates GetLoginDefault with default headers values
func NewGetLoginDefault(code int) *GetLoginDefault {
	if code <= 0 {
		code = 500
	}

	return &GetLoginDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get login default response
func (o *GetLoginDefault) WithStatusCode(code int) *GetLoginDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get login default response
func (o *GetLoginDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get login default response
func (o *GetLoginDefault) WithPayload(payload *models.Error) *GetLoginDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get login default response
func (o *GetLoginDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLoginDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
