// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetLoginCallbackHandlerFunc turns a function with the right signature into a get login callback handler
type GetLoginCallbackHandlerFunc func(GetLoginCallbackParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetLoginCallbackHandlerFunc) Handle(params GetLoginCallbackParams) middleware.Responder {
	return fn(params)
}

// GetLoginCallbackHandler interface for that can handle valid get login callback params
type GetLoginCallbackHandler interface {
	Handle(GetLoginCallbackParams) middleware.Responder
}

// NewGetLoginCallback creates a new http.Handler for the get login callback operation
func NewGetLoginCallback(ctx *middleware.Context, handler GetLoginCallbackHandler) *GetLoginCallback {
	return &GetLoginCallback{Context: ctx, Handler: handler}
}

/*GetLoginCallback swagger:route GET /cidmcallback login getLoginCallback

Get Login return callback used for OAuth2

Get Loging screen

*/
type GetLoginCallback struct {
	Context *middleware.Context
	Handler GetLoginCallbackHandler
}

func (o *GetLoginCallback) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetLoginCallbackParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
