// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetLoginConfigDetailsHandlerFunc turns a function with the right signature into a get login config details handler
type GetLoginConfigDetailsHandlerFunc func(GetLoginConfigDetailsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetLoginConfigDetailsHandlerFunc) Handle(params GetLoginConfigDetailsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetLoginConfigDetailsHandler interface for that can handle valid get login config details params
type GetLoginConfigDetailsHandler interface {
	Handle(GetLoginConfigDetailsParams, interface{}) middleware.Responder
}

// NewGetLoginConfigDetails creates a new http.Handler for the get login config details operation
func NewGetLoginConfigDetails(ctx *middleware.Context, handler GetLoginConfigDetailsHandler) *GetLoginConfigDetails {
	return &GetLoginConfigDetails{Context: ctx, Handler: handler}
}

/*GetLoginConfigDetails swagger:route GET /login/config/{id} login getLoginConfigDetails

Get Default Login details to display login screen.

Get Login persisted configurations.


*/
type GetLoginConfigDetails struct {
	Context *middleware.Context
	Handler GetLoginConfigDetailsHandler
}

func (o *GetLoginConfigDetails) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetLoginConfigDetailsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
