// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/craguilar/cidm/models"
)

// GetLoginConfigDetailsOKCode is the HTTP code returned for type GetLoginConfigDetailsOK
const GetLoginConfigDetailsOKCode int = 200

/*GetLoginConfigDetailsOK Successful operation

swagger:response getLoginConfigDetailsOK
*/
type GetLoginConfigDetailsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Configuration `json:"body,omitempty"`
}

// NewGetLoginConfigDetailsOK creates GetLoginConfigDetailsOK with default headers values
func NewGetLoginConfigDetailsOK() *GetLoginConfigDetailsOK {
	return &GetLoginConfigDetailsOK{}
}

// WithPayload adds the payload to the get login config details o k response
func (o *GetLoginConfigDetailsOK) WithPayload(payload *models.Configuration) *GetLoginConfigDetailsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get login config details o k response
func (o *GetLoginConfigDetailsOK) SetPayload(payload *models.Configuration) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLoginConfigDetailsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetLoginConfigDetailsNotFoundCode is the HTTP code returned for type GetLoginConfigDetailsNotFound
const GetLoginConfigDetailsNotFoundCode int = 404

/*GetLoginConfigDetailsNotFound Loging not found

swagger:response getLoginConfigDetailsNotFound
*/
type GetLoginConfigDetailsNotFound struct {
}

// NewGetLoginConfigDetailsNotFound creates GetLoginConfigDetailsNotFound with default headers values
func NewGetLoginConfigDetailsNotFound() *GetLoginConfigDetailsNotFound {
	return &GetLoginConfigDetailsNotFound{}
}

// WriteResponse to the client
func (o *GetLoginConfigDetailsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*GetLoginConfigDetailsDefault Unexpected error

swagger:response getLoginConfigDetailsDefault
*/
type GetLoginConfigDetailsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetLoginConfigDetailsDefault creates GetLoginConfigDetailsDefault with default headers values
func NewGetLoginConfigDetailsDefault(code int) *GetLoginConfigDetailsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetLoginConfigDetailsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get login config details default response
func (o *GetLoginConfigDetailsDefault) WithStatusCode(code int) *GetLoginConfigDetailsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get login config details default response
func (o *GetLoginConfigDetailsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get login config details default response
func (o *GetLoginConfigDetailsDefault) WithPayload(payload *models.Error) *GetLoginConfigDetailsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get login config details default response
func (o *GetLoginConfigDetailsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLoginConfigDetailsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
