// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateLoginConfigDetailsHandlerFunc turns a function with the right signature into a update login config details handler
type UpdateLoginConfigDetailsHandlerFunc func(UpdateLoginConfigDetailsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateLoginConfigDetailsHandlerFunc) Handle(params UpdateLoginConfigDetailsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateLoginConfigDetailsHandler interface for that can handle valid update login config details params
type UpdateLoginConfigDetailsHandler interface {
	Handle(UpdateLoginConfigDetailsParams, interface{}) middleware.Responder
}

// NewUpdateLoginConfigDetails creates a new http.Handler for the update login config details operation
func NewUpdateLoginConfigDetails(ctx *middleware.Context, handler UpdateLoginConfigDetailsHandler) *UpdateLoginConfigDetails {
	return &UpdateLoginConfigDetails{Context: ctx, Handler: handler}
}

/*UpdateLoginConfigDetails swagger:route PUT /login/config/{id} login updateLoginConfigDetails

Update loging configuration details

Update login details to an existing login.


*/
type UpdateLoginConfigDetails struct {
	Context *middleware.Context
	Handler UpdateLoginConfigDetailsHandler
}

func (o *UpdateLoginConfigDetails) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateLoginConfigDetailsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
