// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateLoginDetailsHandlerFunc turns a function with the right signature into a update login details handler
type UpdateLoginDetailsHandlerFunc func(UpdateLoginDetailsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateLoginDetailsHandlerFunc) Handle(params UpdateLoginDetailsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateLoginDetailsHandler interface for that can handle valid update login details params
type UpdateLoginDetailsHandler interface {
	Handle(UpdateLoginDetailsParams, interface{}) middleware.Responder
}

// NewUpdateLoginDetails creates a new http.Handler for the update login details operation
func NewUpdateLoginDetails(ctx *middleware.Context, handler UpdateLoginDetailsHandler) *UpdateLoginDetails {
	return &UpdateLoginDetails{Context: ctx, Handler: handler}
}

/*UpdateLoginDetails swagger:route PUT /login login updateLoginDetails

Update loging details

Update login details to an existing login.


*/
type UpdateLoginDetails struct {
	Context *middleware.Context
	Handler UpdateLoginDetailsHandler
}

func (o *UpdateLoginDetails) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateLoginDetailsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
