// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/craguilar/cidm/models"
)

// UpdateLoginDetailsCreatedCode is the HTTP code returned for type UpdateLoginDetailsCreated
const UpdateLoginDetailsCreatedCode int = 201

/*UpdateLoginDetailsCreated Created

swagger:response updateLoginDetailsCreated
*/
type UpdateLoginDetailsCreated struct {
}

// NewUpdateLoginDetailsCreated creates UpdateLoginDetailsCreated with default headers values
func NewUpdateLoginDetailsCreated() *UpdateLoginDetailsCreated {
	return &UpdateLoginDetailsCreated{}
}

// WriteResponse to the client
func (o *UpdateLoginDetailsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
}

// UpdateLoginDetailsUnauthorizedCode is the HTTP code returned for type UpdateLoginDetailsUnauthorized
const UpdateLoginDetailsUnauthorizedCode int = 401

/*UpdateLoginDetailsUnauthorized Authentication information is missing or invalid

swagger:response updateLoginDetailsUnauthorized
*/
type UpdateLoginDetailsUnauthorized struct {
	/*
	  Required: true
	*/
	WWWAuthenticate string `json:"WWW_Authenticate"`
}

// NewUpdateLoginDetailsUnauthorized creates UpdateLoginDetailsUnauthorized with default headers values
func NewUpdateLoginDetailsUnauthorized() *UpdateLoginDetailsUnauthorized {
	return &UpdateLoginDetailsUnauthorized{}
}

// WithWWWAuthenticate adds the wWWAuthenticate to the update login details unauthorized response
func (o *UpdateLoginDetailsUnauthorized) WithWWWAuthenticate(wWWAuthenticate string) *UpdateLoginDetailsUnauthorized {
	o.WWWAuthenticate = wWWAuthenticate
	return o
}

// SetWWWAuthenticate sets the wWWAuthenticate to the update login details unauthorized response
func (o *UpdateLoginDetailsUnauthorized) SetWWWAuthenticate(wWWAuthenticate string) {
	o.WWWAuthenticate = wWWAuthenticate
}

// WriteResponse to the client
func (o *UpdateLoginDetailsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header WWW_Authenticate

	wWWAuthenticate := o.WWWAuthenticate
	if wWWAuthenticate != "" {
		rw.Header().Set("WWW_Authenticate", wWWAuthenticate)
	}

	rw.WriteHeader(401)
}

// UpdateLoginDetailsNotFoundCode is the HTTP code returned for type UpdateLoginDetailsNotFound
const UpdateLoginDetailsNotFoundCode int = 404

/*UpdateLoginDetailsNotFound Loging not found

swagger:response updateLoginDetailsNotFound
*/
type UpdateLoginDetailsNotFound struct {
}

// NewUpdateLoginDetailsNotFound creates UpdateLoginDetailsNotFound with default headers values
func NewUpdateLoginDetailsNotFound() *UpdateLoginDetailsNotFound {
	return &UpdateLoginDetailsNotFound{}
}

// WriteResponse to the client
func (o *UpdateLoginDetailsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*UpdateLoginDetailsDefault Unexpected error

swagger:response updateLoginDetailsDefault
*/
type UpdateLoginDetailsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateLoginDetailsDefault creates UpdateLoginDetailsDefault with default headers values
func NewUpdateLoginDetailsDefault(code int) *UpdateLoginDetailsDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateLoginDetailsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update login details default response
func (o *UpdateLoginDetailsDefault) WithStatusCode(code int) *UpdateLoginDetailsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update login details default response
func (o *UpdateLoginDetailsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update login details default response
func (o *UpdateLoginDetailsDefault) WithPayload(payload *models.Error) *UpdateLoginDetailsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update login details default response
func (o *UpdateLoginDetailsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateLoginDetailsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
