// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/craguilar/cidm/models"
)

// NewUpdateLoginConfigDetailsParams creates a new UpdateLoginConfigDetailsParams object
// with the default values initialized.
func NewUpdateLoginConfigDetailsParams() UpdateLoginConfigDetailsParams {
	var ()
	return UpdateLoginConfigDetailsParams{}
}

// UpdateLoginConfigDetailsParams contains all the bound params for the update login config details operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateLoginConfigDetails
type UpdateLoginConfigDetailsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The Configuration object
	  Required: true
	  In: body
	*/
	Configuration *models.Configuration
	/*Config name
	  Required: true
	  In: path
	*/
	ID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *UpdateLoginConfigDetailsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Configuration
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("configuration", "body"))
			} else {
				res = append(res, errors.NewParseError("configuration", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Configuration = &body
			}
		}

	} else {
		res = append(res, errors.Required("configuration", "body"))
	}

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateLoginConfigDetailsParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.ID = raw

	return nil
}
